sudo: false

addons:
  apt_packages:
    - lib32stdc++6

env:
  - SMVERSION=1.8
  - SMVERSION=1.9

matrix:
  fast_finish: true

install:
  - wget http://sourcemod.net/smdrop/$SMVERSION/ -O - | grep "\.tar\.gz" | sed 's/^.*"sourcemod/sourcemod/;s/\.tar\.gz".*$/.tar.gz/' | tail --lines=1 > sourcemod
  - wget --input-file=sourcemod --base=http://sourcemod.net/smdrop/$SMVERSION/
  - tar -xzf $(cat sourcemod)

before_script:
  - cd addons/sourcemod/scripting
  - chmod +x spcomp
  - mkdir compiled

script: ./compile.sh SaucyPugs.sp
